homeController:
  msg: "hello from application yml"


appconfig:
  app-name: Application name
  app-description: ${appconfig.app-name} is a spring boot component
  app-first-name: joe
  app-email: joe@springboot.org

environments:
  development:
    prop1: dev prop1
    prop2: dev prop2
  test:
    prop1: test prop1
    prop2: test prop2
